name: Test

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Print the version
        run: go version
      - name: Run tests and get coverage
        run: |
          make test-with-coverage
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
