name: Test

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Print the version
        run: go version
      - name: Run tests and get coverage
        run: |
          make test-with-coverage
      - name: Upload coverage to Codecov
        # Ref (About secret token to upload the coverage):
        #   https://docs.codecov.com/docs/about-the-codecov-bash-uploader#flag
        #   https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
